"""Switch to UUID

Revision ID: 107d3ff34357
Revises: 
Create Date: 2026-02-15 03:09:29.152474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '107d3ff34357'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscle_groups_name'), 'muscle_groups', ['name'], unique=True)
    op.create_table('user_bio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_templates_name'), 'workout_templates', ['name'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_bio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_body_logs_user_created', 'body_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('measurement_mode', sa.Enum('WEIGHT_REPS', 'TIME', 'BODYWEIGHT_REPS', name='measurementmode'), nullable=False),
    sa.Column('rest_seconds_preset', sa.Integer(), nullable=True),
    sa.Column('primary_muscle_group_id', sa.UUID(), nullable=True),
    sa.Column('secondary_muscle_group_id', sa.UUID(), nullable=True),
    sa.Column('tertiary_muscle_group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['primary_muscle_group_id'], ['muscle_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secondary_muscle_group_id'], ['muscle_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tertiary_muscle_group_id'], ['muscle_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_primary_muscle_group_id'), 'exercises', ['primary_muscle_group_id'], unique=False)
    op.create_index(op.f('ix_exercises_secondary_muscle_group_id'), 'exercises', ['secondary_muscle_group_id'], unique=False)
    op.create_index(op.f('ix_exercises_tertiary_muscle_group_id'), 'exercises', ['tertiary_muscle_group_id'], unique=False)
    op.create_table('template_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_in_template', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_order', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('set_label', sa.Enum('WARMUP', 'WORKING', 'FAILURE', 'DROP_SET', name='setlabel'), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.Column('pr_type', sa.Enum('WEIGHT', 'VOLUME', 'DURATION', name='prtype'), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sets')
    op.drop_table('template_exercises')
    op.drop_index(op.f('ix_exercises_tertiary_muscle_group_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_secondary_muscle_group_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_primary_muscle_group_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index('ix_body_logs_user_created', table_name='body_logs')
    op.drop_table('body_logs')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_workout_templates_name'), table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_table('user_bio')
    op.drop_index(op.f('ix_muscle_groups_name'), table_name='muscle_groups')
    op.drop_table('muscle_groups')
    # ### end Alembic commands ###
